---
title: "Analysing Data Practical 1: Setup and Revision"
author: "Dr Jennifer Mankin"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
```

# Welcome to Analysing Data!

## Today's Goals

* Get R/RStudio and all important packages installed and running for everyone
* Set up a new project file for this module
* Practice using the Canvas site and a few reminders using R
* Practice QUIZ: How much do you remember?

## Setup

In **every** practical, we will ask you to do the same steps as soon as you arrive:

* Log into OneDrive and Canvas
* Open RStudio via the Software Hub
* Open the Analysing Data project file
* Download and open the worksheet, RMarkdown and data files for that week
* Run the first (setup) code chunk

### Step 1: Log into OneDrive and Canvas

**OneDrive**: Sign in at [Office.com](office.com) with your Sussex email and password

**Canvas**: Sign in at [canvas.sussex.ac.uk](canvas.sussex.ac.uk) with your Sussex email and password

### Step 2: Open RStudio

* Click the Windows or magnifying glass on the toolbar and type "Software Hub", then click on the result to open
* Scroll down to RStudio and launch

### Step 3: Create/open your project

* This week, we will set up the project file that you will use for the rest of the term
  + If you are using your own computer, use [this tutorial](http://milton-the-cat.rocks/learnr/r/r_getting_started/#section-working-in-rstudio) to set up a project. 
* In RStudio, click on File > New project..
  + In the New Project window, select New Directory, then New Project.
  + Under Directory name, type “analysing_data”, and for the subdirectory, choose your OneDrive
  + Then click Create Project
  + In the new analysing_data folder, create three new subfolders: `data`, `images`, and `r_docs`.
* Every week after this, you should open this project as soon as you open RStudio

### Step 4: Download files

* In Canvas, go to the Analysing Data page > Syllabus > click on the current week of term. Right now, it's Week 1.
* Under Files:
  + Save the Markdown file in your `analysing_data` > `r_docs` folder
  + Save the dataset(s) in your `analysing_data` > `data` folder
  
### Step 5: Open the files

* Open the Markdown file.
* Change the author to your name.
* Run the first setup code chunk to load all necessary packages and read in the data.

## You're ready to go!

# Today's Tasks

* The goal of today is to get reacquainted with RStudio and RMarkdown. 
* There are three tasks in the worksheet and Markdown file for you to work on
  + All three draw on things you learned in PAAS
* The challenge tasks may include new functions or new ideas
  + Have a go, but don't worry if you get stuck!

# Practice Quiz

* Every week, we will have **marked** quizzes at the start of every practical
* Today, we will have an **unmarked** practice quiz
  + We will invigilate like a real quiz but this is for **practice only**
  + You can take the practice quiz as many times as you want to practice for next week
  
# Next Week

* Quiz topic: identical to the practice quiz
  + Revise practicals and tutorials from PAAS, and Dr Mankin's Week 1 lecture
