---
title: "Practical Template"
author: "Dr Jennifer Mankin"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
```

## Today's Goals

* [Summary of concepts/learning outcomes]

## Setup

In **every** practical, do these same steps as soon as you arrive:

* Log into OneDrive and Canvas
* Open RStudio via the Software Hub
* Open the Analysing Data project file
* Download and open the worksheet, RMarkdown and data files for the current week
* Run the first (setup) code chunk

## Quiz: Questions

* Before today's quiz, you can ask questions about the lecture and tutorial
* We will answer the top three most upvoted questions
* Ask your question or upvote others!

## Quiz

* Go to Canvas > Analysing Data > Quizzes
* Click on this week's quiz
* Click the magenta "Take this quiz" button
* Enter the number code and begin!

# Guided Practice



# Unguided Tasks

* The goal today is 


  
# Next Week

* Quiz topic: [topic]
  + [List of topics, functions, concepts etc. that will be on the quiz]