---
title: "Report Marking Criteria"
output: html_document
---

# Overall Guidelines

<details class = "faq">
<summary>
## Outstanding or Exceptional Firsts
</summary>
<ans>
* Close to the standard of articles published in academic journals
* Impeccable analysis and presentation
* Creative or unusual new ideas with wide-ranging evidence
* Intiative and originality above and beyond the minimum requirements
</ans></details>
<details class = "faq">
<summary>
## Clear First

* Some degree of originality and invention
* Minimum requirements addressed thoroughly and competently
* Clarity and depth of understanding and insight

## 2.1

* Minimum requirements all met, some done quite well
* Few errors in understanding or execution

## 2.2

* Minimum requirements all met or attempted
* Some errors in understanding or execution

## 3rd

* Minimum requirements barely met, some missed out
* Major errors in understanding or execution

## Marginal Fail

* Minimum requirements not met
* Glaring and avoidable errors (wrong analysis, sections missing, etc.)

## Absolute Fail

* Incomplete, inappropriate for the set task

\ 

# Rubric and Criteria

## Analysis

This component reflects the quality of the statistical analysis and ability to present and interpret data. To score highly in this area, the student must write their code and run their analysis thoroughly and correctly, report all the relevant statistics clearly and correctly, visualise their data appropriately, and demonstrate how well they understand what the results mean.

### Outstanding (82, 88) or Exceptional (95) First

* Excellent data analysis and presentation
* Correctly executed analysis appropriate to address the research question
* Exceptionally clear and coherent presentation that implies a full understanding of visualising, analysing, describing, and interpreting data
* Use of or innovation in analytic tools beyond what has been taught

### Clear First (72, 75, 78)

* Excellent data analysis and presentation
* Correctly executed analysis appropriate to address the research question
* Coherent presentation that implies a full understanding of visualising, analysing, describing, and interpreting data

### 2.1 (62, 65, 68)

* Competent data analysis and presentation
* Correctly executed analysis appropriate to address the research question
* Generally coherent presentation that implies a good understanding of visualising, analysing, describing, and interpreting data

### 2.2 (52, 55, 58)

* Minor deficiencies in data analysis and presentation
* Analysis partially appropriate to address the research question and/or minor errors in execution
* Presentation with occasional lapses in coherence, or that implies confusion about visualising, analysing, describing, and interpreting data

### 3rd (42, 45, 48)

* Moderate deficiencies in data analysis and presentation
* Analysis inappropriate to address the research question and/or errors in execution
* Presentation lacks coherence, or demonstrates little understanding of visualising, analysing, describing, and interpreting data

### Marginal Fail (35, 38)

* Serious deficiencies in data analysis and presentation
* Analysis inappropriate to address the research question and/or incorrected executed
* Presentation cursory, incoherent, and/or demonstrates lack of understanding of visualising, analysing, describing, and interpreting data

### Absolute Fail (0, 10, 20, 30)

* No analysis attempted, or one so ill-concieved as to demonstrate virtually no understanding of visualising, analysing, describing, and interpreting data

\ 

## Critical Thinking

This component captures the ability to evaluate the student's own and other studies' findings with a critical eye. To score highly in this area, the student must discuss evidence-based criticisms of their own and other studies (not just speculations about what might have gone wrong!); and make insightful, novel, or theoretically interesting suggestions for how to continue this research in the future.

### Outstanding (82, 88) or Exceptional (95) First

* Excellent or high level of ability to criticise constructively both past research and the research that has been performed (both on methodological and theoretical grounds)
* Insightful and worthwhile suggestions for future research

### Clear First (72, 75, 78)

* Some ability to criticise constructively both past research and the research that has been performed (both on methodological and theoretical grounds)
* Insightful and worthwhile suggestions for future research

### 2.1 (62, 65, 68)

* Some attempt to criticise constructively their own and past research (both on methodological and theoretical grounds), but these may contain some trivial observations. 
* Sensible suggestions for future research are made

### 2.2 (52, 55, 58)

* The student has demonstrated a lack of ability to constructively criticise their own or past research (either on methodological or theoretical grounds) or to suggest worthwhile future research.

### 3rd (42, 45, 48)

* Little evidence of any ability to evaluate the theoretical or methodological limitations of the study performed are presented.

### Marginal Fail (35, 38)

* There is no evidence of any ability to evaluate the theoretical or methodological limitations of the study performed.

### Absolute Fail (0, 10, 20, 30)

No attempt to evaluate the theoretical or methodological limitations of the study has been performed.

\ 

## Theoretical Understanding

This component looks at the knowledge and understanding of both the research question and the analysis that has been done to answer it. To score highly in this area, the student must demonstrate that they understand what their analysis means, and discuss how their analysis results do, and do not, inform the overall research question. 

### Outstanding (82, 88) or Exceptional (95) First

* The discussion show an excellent understanding of the theoretical issues underlying the research. 
* The discussion demonstrates an insightful grasp of the theoretical implications of the work.

### Clear First (72, 75, 78)

* Reasonable understanding of theoretical and methodological issues. 
* The discussion shows a good understanding of the theoretical issues underlying the research.

### 2.1 (62, 65, 68)

* The discussion includes a competent attempt to relate the findings to previous theoretical and empirical research. 
* However, the exposition of theoretical implications is less than in higher bands.

### 2.2 (52, 55, 58)

* A limited attempt to relate the study to previous work (theoretical and empirical) was made.

### 3rd (42, 45, 48)

* Little attempt to relate the results to relevant theoretical background material is apparent.

### Marginal Fail (35, 38)

* There is a complete lack of theoretical insight.

### Absolute Fail (0, 10, 20, 30)

* There is a complete lack of theoretical insight.

\ 

## Organisation

This component captures the quality of writing, both of text and of R script, and the ability to communicate clearly and scientifically. To score highly in this area, the student must write clear, error-free, efficient R code; submit an RMarkdown file that knits correctly and produces a consistently and correctly formatted document; organise their report into sections, each of which summarises the relevant information accurately and succinctly; and communicate their ideas, findings, and evidence in a logical, scientific, and understandable way.

### Outstanding (82, 88) or Exceptional (95) First

* Outstanding study and write-up that shows initiative, flair, and originality. 
* The write-up is exceptional in terms of clarity and organisation of material, with little evidence of wandering off on tangents.
* Few or no errors in format conventions.

### Clear First (72, 75, 78)

* The write-up is well organised and clearly written. 
* The discussion may be slightly less focused than for higher marking bands but largely avoids mentioning work not directly relevant to the current research. 
* There can be minor errors in terms of adherence to project format conventions.

### 2.1 (62, 65, 68)

* The write-up is fairly well organised and clearly written (possibly with some minor lapses of clarity).
* The discussion may not be as focused as in higher marking bands but the key relevant material is included.
* Some errors in adherence to project format guidelines will be tolerated.

### 2.2 (52, 55, 58)

* Adequately organised and moderately competent project
* Some of the following limitations: lack of adherence to standard format, poor organisation of material, poor or clumsy expression.

### 3rd (42, 45, 48)

* Basic information about the research is communicated, but there is little attention to comprehensiveness or clarity in describing the procedures used or the results obtained.
* Presentation is somewhat scrappy.

### Marginal Fail (35, 38)

* Incomplete or badly written up. 
* Very little effort has been put into describing the method, results and relevant background theory and research. 
* There is incoherence in presentation of background material, procedures, or analysis.

### Absolute Fail (0, 10, 20, 30)

* There is barely any attempt to mention relevant background theory and research, and to describe the method and results.

\ 

## Research

Sensible and evidence-based design; clear and detailed explanation of experimental design and variables; breadth and depth of reading; application of readings to ideas and interpretation

### Outstanding (82, 88) or Exceptional (95) First

* Evidence of independent reading of relevant research (from up-to-date journal articles and books). 
* The design is very good in terms of originality, methodological rigour, and theoretical significance.

### Clear First (72, 75, 78)

* Evidence of some independent reading of relevant research (from up-to date-journalarticles and books), supplementing references already provided on the reading list. 
* The design is good in terms of originality, methodological rigour and theoretical significance.

### 2.1 (62, 65, 68)

* Background material used for the introduction and discussion does not go substantially beyond that mentioned on the reading list. 
* A competently designed and methodologically rigorous study.

### 2.2 (52, 55, 58)

* Background material used for the discussion is limited to the reading list.
* The design is adequate in terms of methodological rigour. 

### 3rd (42, 45, 48)

* The design has some merit but has major methodological flaws or limitations that could have been foreseen and avoided.

### Marginal Fail (35, 38)

* The design is inadequate to address the research issue.

### Absolute Fail (0, 10, 20, 30)

* Either no study was conducted or it was so poorly conceived as to be of no consequence whatsoever for the research issue.

\ 
